apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-k8s
spec:
  selector:
    matchLabels:
      name: node-api-k8s
  replicas: 1
  template:
    metadata:
      labels:
        name: node-api-k8s
    spec:
      containers:
      - name: node-api-k8s
        image: jthueux/node-kube-image:oxylib
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
