apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node
  name: node-api-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-api-k8s
    spec:
      containers:
      - name: node-api-k8s
        image: jthueux/node-kube-image:oxylib
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
