apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-api-k8s
  template:
    metadata:
      labels:
        name: node-api-k8s
    spec:
      containers:
        - name: node-api-k8s
          image: jthueux/node-kube-image:test2
          ports:
            - containerPort: 3001