apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 3001
  type: NodePort