apiVersion: v1
kind: Service
metadata:
  name: node-api-k8s
  labels:
    app: node
spec:
  ports:
      - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31000
  selector:
    app: node
  type: NodePort
