apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    name: node-app-service
spec:
  type: NodePort
  selector:
    name: node-app
    app: node-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32000