apiVersion: v1
kind: Service
metadata:
  name: node-api-k8s
  labels:
    app: node-api-k8s
spec:
  selector:
    app: node-api-k8s
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31000
status:
  loadBalancer: {}
