apiVersion: v1
kind: Service
metadata:
  name: node-api-k8s
  labels:
    app: node-api-k8s
spec:
  type: NodePort
  selector:
    name: node-api-k8s
    app: node-api-k8s
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32000
status:
  loadBalancer: {}