apiVersion: v1
kind: Service
metadata:
  name: node-api-k8s
  labels:
    app: node
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
    nodePort: 31000
  selector:
    app: node
  type: NodePort
