apiVersion: v1
kind: Service
metadata:
  name: node-api-k8s
  labels:
    app: node-api-k8s
spec:
  type: NodePort
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
      name: node-api-k8s
