apiVersion: v1
kind: Service
metadata:
  name: mongo-app-service
spec:
  selector:
    app: mongo-app
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 8081
  type: NodePort